version: "3.8"

services:
  opensearch-node:
    image: "opensearchproject/opensearch:${OPENSEARCH_VERSION}"
    container_name: "${OPENSEARCH_NODE_NAME}"
    restart: ${RESTART_POLICY}
    environment:
      cluster.name: ${OPENSEARCH_CLUSTER_NAME}
      node.name: ${OPENSEARCH_NODE_NAME}
      discovery.type: ${OPENSEARCH_DISCOVERY_TYPE}
      bootstrap.memory_lock: ${OPENSEARCH_MEMORY_LOCK}
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      OPENSEARCH_JAVA_OPTS: ${OPENSEARCH_JAVA_OPTS}
      DISABLE_SECURITY_PLUGIN: ${OPENSEARCH_NODE_SECURITY_DISABLED}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/usr/share/opensearch/data
    ports:
      - "${OPENSEARCH_HTTP_PORT}:9200"
      - "${OPENSEARCH_PERF_ANALYZER_PORT}:9600"
    networks:
      - opensearch

  opensearch-dashboards:
    image: "opensearchproject/opensearch-dashboards:${OPENSEARCH_DASHBOARDS_VERSION}"
    container_name: "${OPENSEARCH_DASHBOARDS_CONTAINER}"
    restart: ${RESTART_POLICY}
    ports:
      - "${OPENSEARCH_DASHBOARDS_PORT}:5601"
    environment:
      OPENSEARCH_HOSTS: ${OPENSEARCH_HOSTS}
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: ${DASHBOARDS_SECURITY_DISABLED}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
    depends_on:
      - opensearch-node
    networks:
      - opensearch

networks:
  opensearch:
    name: ${OPENSEARCH_NETWORK}
    driver: bridge

volumes:
  data:
    name: ${OPENSEARCH_DATA_VOLUME}
    driver: local
